import React from 'react';
import { useState, useEffect } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import Reseaux from './components/Reseaux'
import Loader from "./components/Loader";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faArrowRightLong } from "@fortawesome/free-solid-svg-icons";

const Home = () => {

    const [loading, setLoading] = useState(true);

    useEffect(() => {
        setTimeout(() => {
            setLoading(false);
        }, 6000);
    }, []);

    if (loading) {
        return <Loader />;
    }

    return (
        <>
            <Head>
                <title>BENADJAL DRISS PORTFOLIO</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <Reseaux />
            <header>
                <section className='ath'>
                    <div className='container-trait'>
                        <div className='trait'></div>
                    </div>
                    <Link href="/">
                        <div className='container-text'>
                            <h3>SCROLL </h3>
                            <FontAwesomeIcon icon={faArrowRightLong} />
                        </div>
                    </Link>
                </section>
                <section className='content'>
                    <div className="perspective-text">
                        <div className="perspective-line">
                            <p>BENADJAL</p>
                            <p>DRISS</p>
                        </div>
                        <div className="perspective-line">
                            <p>DRISS</p>
                            <p>BENADJAL</p>
                        </div>
                        <div className="perspective-line">
                            <p>BENADJAL</p>
                            <p>DRISS</p>
                        </div>
                    </div>
                    <video id='video' src='./video/ia.mp4/' autoPlay muted loop />
                </section>
                {/* <h1 id='text-header'>FULL-STACK</h1> */}
            </header>
            <main>
                
            </main>
        </>
    )
}

export default Home;