import React from 'react';
import { useState, useEffect } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import Reseaux from './components/Reseaux'
import Loader from "./components/Loader";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faArrowRightLong } from "@fortawesome/free-solid-svg-icons";

const Home = () => {

    const [loading, setLoading] = useState(true);

    useEffect(() => {
        setTimeout(() => {
            setLoading(false);
        }, 6000);
    }, []);

    if (loading) {
        return <Loader />;
    }

    return (
        <>
            <Head>
                <title>BENADJAL DRISS PORTFOLIO</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <h1 id='text-name'>DRISS BENADJAL</h1>
            <Reseaux />
            <header>
                <div className='ath'>
                    <div className='container-trait'>
                        <div className='trait'></div>
                    </div>
                    <Link href="/">
                        <div className='container-text'>
                            <h3>SCROLL </h3>
                            <FontAwesomeIcon icon={faArrowRightLong} />
                        </div>
                    </Link>
                </div>
                <video id='video' src='./video/ia.mp4/' autoPlay muted loop />
                <h1 id='text-header'>FULL-STACK</h1>
            </header>
            <main>
                <div id="roadmap-container" className="roadmap-container">
                    <div className="roadmap-auto">
                        <h2 className="roadmap-h2">Roadmap</h2>
                        <div className="spacer-block">&nbsp;</div>
                        <div className="roadmap-timeline">
                            <div className="timeline-dot">&nbsp;</div>
                            <div className="timeline-list">
                                <div className="timeline-list-vr">&nbsp;</div>
                                <div className="timeline-list-col timeline-col-left">
                                    <div className="timeline-item-block timeline-item-block-green">
                                        <div className="timeline-item-time">
                                            <div className="timeline-item-label">2018 - 2021</div>
                                        </div>
                                        <div className="timeline-item-label-hr">
                                            <div className="item-dot timeline-dot">&nbsp;</div>
                                        </div>
                                        <div className="timeline-item-label2">BAC STI2D SIN</div>
                                        <div className="timeline-item-content">
                                            <p>LYCÉE RENÉ CASSIN LE RAINCY</p>
                                        </div>
                                    </div>

                                    <div className="timeline-item-block timeline-item-block-mobile timeline-item-block-violet">
                                        <div className="timeline-item-time">
                                            <div className="timeline-item-label">2021 - 2024</div>
                                        </div>
                                        <div className="timeline-item-label-hr">
                                            <div className="item-dot timeline-dot">&nbsp;</div>
                                        </div>
                                        <div className="timeline-item-label2">B.U.T MMI</div>
                                        <div className="timeline-item-content">
                                            <p>Bitair payment solution into real business network regarding booking airline ticket (trial version) to conduct research</p>
                                            <p>Make survey of users experiences & choices</p>
                                            <p>Approach airlines, travel & tourism agencies regarding a new, fast, cheap, reliable payment method.</p>
                                            <p>Develop application iOS and Android</p>
                                        </div>
                                    </div>


                                    <div className="timeline-item-block timeline-item-block-blue">
                                        <div className="timeline-item-time">
                                            <div className="timeline-item-label">2017 Q2</div>
                                        </div>
                                        <div className="timeline-item-label-hr">
                                            <div className="item-dot timeline-dot">&nbsp;</div>
                                        </div>
                                        <div className="timeline-item-label2">Opening New Business</div>
                                        <div className="timeline-item-content">
                                            <p>Finish necessarily legal procedure to able to operate across many regions / nations</p>
                                            <p>Fulfill human requirement and head-hunting work</p>
                                        </div>
                                    </div>

                                    <div className="timeline-item-block timeline-item-block-mobile timeline-item-block-green2">
                                        <div className="timeline-item-time">
                                            <div className="timeline-item-label">2017 Q3</div>
                                        </div>
                                        <div className="timeline-item-label-hr">
                                            <div className="item-dot timeline-dot">&nbsp;</div>
                                        </div>
                                        <div className="timeline-item-label2">ICO and IPO</div>
                                        <div className="timeline-item-content">
                                            <p>Late August: Presale period</p>
                                            <p>Token sale Event</p>
                                            <p>September: Initial Coin Offering (ICO) period</p>
                                            <p>Mid-September: Prepare for initial Public Offering (IPO) period</p>
                                        </div>
                                    </div>

                                    <div className="timeline-item-block timeline-item-block17q4 timeline-item-block-green">
                                        <div className="timeline-item-time">
                                            <div className="timeline-item-label">2017 Q4</div>
                                        </div>
                                        <div className="timeline-item-label-hr">
                                            <div className="item-dot timeline-dot">&nbsp;</div>
                                        </div>
                                        <div className="timeline-item-label2">LISTING BTCA ON EXCHANGES</div>
                                        <div className="timeline-item-content">
                                            <p>Early October, prepare full project to submit BTCA to Exchanges.</p>
                                            <p>Target to list on other top Exchanges such as: Hitbtc</p>
                                        </div>
                                    </div>


                                    <div className="timeline-item-block timeline-item-block-mobile timeline-item-block-blue">
                                        <div className="timeline-item-time">
                                            <div className="timeline-item-label">2018 Q1</div>
                                        </div>
                                        <div className="timeline-item-label-hr">
                                            <div className="item-dot timeline-dot">&nbsp;</div>
                                        </div>
                                        <div className="timeline-item-label2">Globalizing Bitair System</div>
                                        <div className="timeline-item-content">
                                            <p className="no-bullet">Reach agreement on deploying Bitair payment solution via top ten chosen global websites such as: Expedia.com, Travelport.com, Cheapadvisor.com, Booking.com, Agoda.com</p>
                                        </div>
                                    </div>

                                    <div className="timeline-item-block timeline-item-block18q2 timeline-item-block-violet">
                                        <div className="timeline-item-time">
                                            <div className="timeline-item-label">2018 Q2</div>
                                        </div>
                                        <div className="timeline-item-label-hr">
                                            <div className="item-dot timeline-dot">&nbsp;</div>
                                        </div>
                                        <div className="timeline-item-label2">And Further</div>
                                        <div className="timeline-item-content">
                                            <p>Strengthen the partnership and enhance marketing campaign.</p>
                                            <p>Distribute token revenue and holder income.</p>
                                        </div>
                                    </div>

                                </div>

                                <div className="timeline-list-col timeline-col-right">

                                    <div className="timeline-item-block timeline-item-block-right timeline-item-block-violet">
                                        <div className="timeline-item-time">
                                            <div className="timeline-item-label">2017 Q1</div>
                                        </div>
                                        <div className="timeline-item-label-hr">
                                            <div className="item-dot timeline-dot">&nbsp;</div>
                                        </div>
                                        <div className="timeline-item-label2">Buiding Up And Getting Real Experiences</div>
                                        <div className="timeline-item-content">
                                            <p>Integrate Bitair payment solution into real business network regarding booking airline ticket (trial version) to conduct research</p>
                                            <p>Make survey of users experiences & choices</p>
                                            <p>Approach airlines, travel & tourism agencies regarding a new, fast, cheap, reliable payment method.</p>
                                            <p>Develop application iOS and Android</p>
                                        </div>
                                    </div>

                                    <div className="timeline-item-block timeline-item-block-right timeline-item-block-green2">
                                        <div className="timeline-item-time">
                                            <div className="timeline-item-label">2017 Q3</div>
                                        </div>
                                        <div className="timeline-item-label-hr">
                                            <div className="item-dot timeline-dot">&nbsp;</div>
                                        </div>
                                        <div className="timeline-item-label2">ICO and IPO</div>
                                        <div className="timeline-item-content">
                                            <p>Late August: Presale period</p>
                                            <p>Token sale Event</p>
                                            <p>September: Initial Coin Offering (ICO) period</p>
                                            <p>Mid-September: Prepare for initial Public Offering (IPO) period</p>
                                        </div>
                                    </div>

                                    <div className="timeline-item-block timeline-item-block-right timeline-item-block-blue">
                                        <div className="timeline-item-time">
                                            <div className="timeline-item-label">2018 Q1</div>
                                        </div>
                                        <div className="timeline-item-label-hr">
                                            <div className="item-dot timeline-dot">&nbsp;</div>
                                        </div>
                                        <div className="timeline-item-label2">Globalizing Bitair System</div>
                                        <div className="timeline-item-content">
                                            <p className="no-bullet">Reach agreement on deploying Bitair payment solution via top ten chosen global website</p>
                                        </div>
                                    </div>

                                </div>

                            </div>

                        </div>
                    </div>
                </div>
            </main>
        </>
    )
}

export default Home;